### ISSUE TITLE
Documentation of docker run with s3-manager

### ISSUE THREAD

**Issue by sspreitzer** [mastertinner/s3-manager#2]
Hi

A short documentation about how to build and how to run s3-manager with native Docker would be awesome!

Kind regards
Sascha

**Comment by mastertinner** [comment]
Thanks, @sspreitzer! I added some documentation to the README.md and added a Dockerfile and a docker-compose.yml which should help you to accomplish everything you need with Docker.

**Comment by MickL** [comment]
@mastertinner Where is this docker-compose.yml? Also I did not notice the Dockerfile, maybe you can add a link to it (and docker-compose.yml) in the readme so everyone notices it?

**Comment by mastertinner** [comment]
There is currently no `docker-compose.yml` anymore because the app is so basic and providing a generic one is not really possible. The `Dockerfile` is right at the root of the repo.
